### ISSUE TITLE
no such table: "language"

### ISSUE THREAD

**Issue by DwarfLop** [y21/wiiset-bot#8]
You can add an query which creates the "language" table (for self hosting the bot, I'll create an pull request and I can't start the bot bc of that error).

**Comment by y21** [comment]
Oh, thank you for your report. I will fix that as soon as possible.

**Comment by y21** [comment]
Fixed in <https://github.com/y21/wiiset-bot/commit/77ad3685be483b79ec9543ecc9dde36f95e18db9>.

**Comment by DwarfLop** [comment]
Thanks!
